version: '3'

services:

  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - "6379:6379"
    # network_mode: host

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp
    command: gunicorn --bind 0.0.0.0:8000 webapp.app:server
    ports:
      - "8000:8000"
    # network_mode: host
    depends_on:
      - redis
    environment:
      - FLASK_SECRET_KEY=pP3&L4N:o9q'E_#@/fqo8mDL&VFvvB