version: '3'

services:

  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - "6379:6379"
    # network_mode: host

  webapp:
    build:
      context: .
      dockerfile: quant_tradr/webapp/Dockerfile
    container_name: webapp
    command: gunicorn --bind 0.0.0.0:8000 quant_tradr.webapp.app:server
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - FLASK_SECRET_KEY=pP3&L4N:o9q'E_#@/fqo8mDL&VFvvB
    # network_mode: host

  nginx:
    build:
      context: .
      dockerfile: quant_tradr/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - webapp
    # network_mode: host