version: '3'

services:
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - "6379:6379"

  webapp:
    build:
      context: .
      dockerfile: quant_tradr/webapp/Dockerfile
    container_name: webapp
    depends_on:
      - redis
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      network: host
      args:
        - CERTBOT_EMAIL=david.a.gorski@gmail.com
        - DOMAIN_LIST=dg-quant-tradr.com
    restart: always
    depends_on:
      - webapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

volumes:
  letsencrypt:
