name: Deploy to AWS with Docker Compose
on:
  push:
    branches:
      - master

env:
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Set Environment Variables and Create secrets.env
        run: |
          echo "CERTBOT_EMAIL=\"${{ secrets.CERTBOT_EMAIL }}\"" >> $GITHUB_ENV
          echo "DOMAIN_LIST=\"${{ secrets.DOMAIN_LIST }}\"" >> $GITHUB_ENV
          echo "FLASK_SECRET_KEY=\"${{ secrets.FLASK_SECRET_KEY }}\"" >> $GITHUB_ENV
          echo "CERTBOT_EMAIL=\"${{ secrets.CERTBOT_EMAIL }}\"" > secrets.env
          echo "DOMAIN_LIST=\"${{ secrets.DOMAIN_LIST }}\"" >> secrets.env
          echo "FLASK_SECRET_KEY=\"${{ secrets.FLASK_SECRET_KEY }}\"" >> secrets.env
     

      
      - name: Copy Docker Compose file to EC2 instance
        run: |
          scp -r -o StrictHostKeyChecking=no -i key.pem secrets.env ${GITHUB_WORKSPACE}/* ubuntu@ec2-44-219-245-255.compute-1.amazonaws.com:/home/ubuntu


      - name: Connect to EC2 instance and deploy Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-44-219-245-255.compute-1.amazonaws.com 'cd /home/ubuntu && sudo docker-compose stop && sudo docker-compose down && sudo docker-compose --env-file secrets.env up -d'
