name: Deploy to AWS with Docker Compose
on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: PROD

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set permissions for private key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
          
      - name: Create secrets.env
        run: |
          echo "CERTBOT_EMAIL=\"${{ secrets.CERTBOT_EMAIL }}\"" > secrets.env
          echo "DOMAIN_LIST=\"${{ secrets.DOMAIN_LIST }}\"" >> secrets.env
          echo "FLASK_SECRET_KEY=\"${{ secrets.FLASK_SECRET_KEY }}\"" >> secrets.env

      - name: Clean up files then copy files
        env:
          USER: ${{ secrets.USER }}
          PUBLIC_IPV4: ${{ secrets.PUBLIC_IPV4 }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$PUBLIC_IPV4 'cd /home/$USER && rm -rf app/ && mkdir app/'
          scp -r -o StrictHostKeyChecking=no -i key.pem secrets.env ${GITHUB_WORKSPACE}/* $USER@$PUBLIC_IPV4:/home/$USER/app

      - name: Deploy docker compose
        env:
          USER: ${{ secrets.USER }}
          PUBLIC_IPV4: ${{ secrets.PUBLIC_IPV4 }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$PUBLIC_IPV4 'cd /home/$USER/app && sudo docker-compose down && sudo docker-compose --env-file secrets.env up -d'
