name: Deploy to AWS with Docker Compose
on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: PROD

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
          
      - name: Create secrets.env
        run: |
          echo "CERTBOT_EMAIL=\"${{ secrets.CERTBOT_EMAIL }}\"" > secrets.env
          echo "DOMAIN_LIST=\"${{ secrets.DOMAIN_LIST }}\"" >> secrets.env
          echo "FLASK_SECRET_KEY=\"${{ secrets.FLASK_SECRET_KEY }}\"" >> secrets.env

      - name: Clean up files then copy files
        env:
          USER: ${{ secrets.USER }}
        run: |
          echo $USER | sed 's/./& /g'
          rm -rf /home/$USER/app/
          mkdir /home/$USER/app/
          scp -r -o StrictHostKeyChecking=no -i key.pem secrets.env ${GITHUB_WORKSPACE}/* $USER@${{ secrets.PUBLIC_IPV4 }}:/home/${{ secrets.USER }}/app

      - name: Deploy docker compose
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.USER }}@${{ secrets.PUBLIC_IPV4 }} 'cd /home/${{ secrets.USER }}/app && sudo docker-compose down && sudo docker-compose --env-file secrets.env
